### PR TITLE
issue #1 fixing deprecated variable ansible_eth1

### PR DESCRIPTION
**Pull request by ledroide**

### CODE REVIEW

**Review by karras — COMMENTED** [review]
@tongpu looks good to me!

**Comment by tongpu** [comment]
This only fixes the issue when you only have a single interface. My goal was to split external and internal cluster traffic over multiple interfaces. I would need to further look into that for a final fix.

**Comment by tongpu** [comment]
This issue is being fixed in #3 by making the interface for internal cluster traffic configurable, because of that I'm going to close this PR when #3 is being merged.

**Comment by tongpu** [comment]
#3 introduced the possibility to configure the interface to be used for Galera cluster communication using the variable `galera_cluster_interface`.
PR is being closed, because of that.

**Comment by copdips** [comment]
@tongpu 

`ansible_eth1_ipv4 doesnt` exit, `ansible_default_ipv4` works, #3 doesnt fix the issue. #1 is good at least for my env.

**Comment by tongpu** [comment]
@copdips When you specify `galera_cluster_interface` the approach in #3 should work. What version of Ansible are you using?

**Comment by copdips** [comment]
@tongpu 

```
# ansible --version
ansible 2.7.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr 11 2018, 07:36:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```
```
# ansible -m setup localhost | grep eth
            "type": "ether"
            "type": "ether"
```

**Comment by tongpu** [comment]
@copdips You need to set the variable `galera_cluster_interface` to the name of the interface that you've designated for the cluster communication. I've set the default to `eth1` for this demo, but you would need to specify the interface you want to use.

**Pull request closed without merging**
